version: '3.3'

services:
  my-notes-project:
    build: server
    command: ./prog
    volumes:
      - ./database:/database
    ports:
      - 8080:8080
    environment:
      - DATABASE_PATH=/database/noteuser.db

